version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: conduit_pr
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=notesDB
    volumes:
      - db_pg_dart:/var/lib/postgresql/data/
    command:
       - "postgres"
      - "-c"
      - "port=5432"

  api:
    container_name: api_pr
    build: . 
    ports:
      - 8888:8888

volumes:
  db_vol:
